config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :categories do
    resources :payments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#welcome"
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :name, presence: true, length: { minimum: 1, maximum: 40 }
  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @category = Category.find(params[:category_id])
    @payments = @category.payments
  end

  # GET /payments/1 or /payments/1.json
  def show
    @category = Category.find(params[:category_id])
    @payment = Payment.find(params[:id])
  end

  # GET /payments/new
  def new
    @category = Category.find(params[:category_id])
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
    @category = Category.find(params[:category_id])
    @payment = Payment.find(params[:id])
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user = current_user
    @category = Category.last
    @payment.categories.push(@category)

    respond_to do |format|
      if @payment.save

        format.html { redirect_to category_payments_path(@category), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    @category = Category.find(params[:category_id])

    respond_to do |format|
      if @payment.update(payment_params)
        format.html do
          redirect_to category_payment_path(@category, @payment), notice: 'Payment was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to category_payments_path, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, :user_id)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, url: category_payments_path([:category_id])) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  
  <div class="payment-view">
<div class="payment-line">
 <%= link_to category_payment_path(@category, payment) do %>
    
  <p>
    <strong><%= payment.name %></strong>
  </p>

<% end %>


  <p>$ <%= payment.amount %></p>
  
  
  </div>
<p>Date & time: <%= payment.created_at %></p>

</div>
</div>

app/views/payments/edit.html.erb
<div class="edit-category">

<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  
  <%= link_to "Back to payments", category_payments_path, class: "links-edit-back-see"  %>
</div>
</div>

app/views/payments/index.html.erb
<div class="payments-view">

<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">

<div class="render-payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    
  <% end %>
</div>
</div>

<div class="links-list">

<%= link_to "Back to category", category_path(@category), class: "links-edit-back-see" %> |

<%= link_to "New payment", new_category_payment_path, class: "links-edit-back-see" %>

</div>
</div>

app/views/payments/new.html.erb
<div class="edit-category">

<h1>New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", category_payments_path %>
</div>

</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div class="links-list">
 
  <%= link_to "Back to payments", category_payments_path, class: "links-edit-back-see"  %>
</div>
  
  <div class="destroy-button-div">
  <%= button_to "Destroy this Payment", @payment_path, method: :delete, class: "destroy-button"  %>

</div>