config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :categories do
    resources :payments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#welcome"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_and_belongs_to_many :payments

  validates :name, presence: true, length: { minimum: 1, maximum: 40 }
  validates :icon, presence: true

  def total_amount_category
    total = 0
    payments.each do |payment|
      total += payment.amount
    end
    total.round(2)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  
  <%= link_to category do %>
  <div class="render-category">  
  
    <img class="newcategory_img" src="<%=asset_path("#{category.icon}.png") %>">
   <% end %>
    
    <p class="category-name-amount-link">
      <strong><%= category.name %></strong>
    </p>

    <p class="category-name-amount-link">
      $ <%= category.total_amount_category %>
    </p>

  </div>
 
</div>

app/views/categories/_form.html.erb
<% icon_list =[
    {
      icon: 'airplane',
      title: 'airplane',
    },
    {
      icon: 'art',
      title: 'art',
    },
    {
      icon: 'car',
      title: 'car',
    },
    {
      icon: 'entertainment',
      title: 'entertainment',
    },
    {
      icon: 'fashion',
      title: 'fashion',
    },
    {
      icon: 'food',
      title: 'food',
    },
    {
      icon: 'furniture',
      title: 'furniture',
    },
    {
      icon: 'health',
      title: 'health',
    },
    {
      icon: 'home',
      title: 'home',
    },
    {
      icon: 'insurance',
      title: 'insurance',
    },
    {
      icon: 'medicine',
      title: 'medicine',
    },
    {
      icon: 'movie',
      title: 'movie',
    },
    {
      icon: 'music',
      title: 'music',
    },
    {
      icon: 'pet',
      title: 'pet',
    },
    {
      icon: 'restaurant',
      title: 'restaurant',
    },
    {
      icon: 'shoe',
      title: 'shoe',
    },
    {
      icon: 'sport',
      title: 'sport',
    },
    {
      icon: 'studying',
      title: 'studying',
    },
    {
      icon: 'tech',
      title: 'tech',
    },
    {
      icon: 'transportation',
      title: 'transportation',
    },
] %>

<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="editing-category-name">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  

<p>Please, select an icon from the list:</p>
    
    <ul class="newcategory">
    
    <% icon_list.each do |icon_option|%>
      <li class="newcategory-option-list">
        <%= form.radio_button :icon, icon_option[:icon] %> 
        <img class="newcategory_img" src="<%=asset_path("#{icon_option[:icon]}.png") %>" alt=<%=icon_option[:title]%>>
      </li>
       <% end %>
    </ul>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="edit-category">

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div class="links-list">
  <%= link_to "Show this category", @category, class: "links-edit-back-see" %> |
  <%= link_to "Back to categories", categories_path, class: "links-edit-back-see" %>
</div>
</div>

app/views/categories/index.html.erb
<div class="categories-view">

<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
   
   <div class="single-category">
     
     <%= render category %>
     
    </div>

  <% end %>

  </div>
  
<div class="new-category-button-div">

<%= link_to "New category", new_category_path, class: "new-category-button" %>

</div>

app/views/categories/new.html.erb
<div class="edit-category">

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path, class: "links-edit-back-see" %>
</div>
</div>

app/views/categories/show.html.erb
<div class="show-category">

<p style="color: green"><%= notice %></p>

<%= render @category %>

<div class="links-list">

  <%= link_to "Edit this category", edit_category_path(@category), class: "links-edit-back-see" %> |
  <%= link_to category_payments_path(@category), class: "links-edit-back-see" do %>See Payments<% end %> |
  <%= link_to "Back to categories", categories_path, class: "links-edit-back-see" %> 
 </div>
  
  <div class="destroy-button-div">
  <%= button_to "Destroy this category", @category, method: :delete, class: "destroy-button" %>
 </div>


</div>